### ISSUE TITLE
commenttype setting problem

### ISSUE THREAD

**Issue by pintergreg** [micro-editor/comment-plugin#1]
Thank you for implementing the comment line function so quickly, but I think there is some problem with it.
It produces "/* %s */" for every file type I tried irrespectively of the set file type.

I tried to get more information and I found out if I set the commenttype through a manual command it (e.g. set commenttype "# %s") it uses the new value, but the automatic commenttype setting seems not to work. At least, it seems the else branch is executed.

![micro_comment](https://cloud.githubusercontent.com/assets/3854784/20211111/4c2d32b2-a7fd-11e6-93ef-93398fa98a6b.png)

**Comment by zyedidia** [comment]
I think the problem was caused by changing the filetype after opening a file that had no filetype.

**Comment by pintergreg** [comment]
You are right! Indeed, I tested with a new document. The previous version was also worked if I opened a ruby file (for example). Now it works properly with manually changed file type as well.
Thank you!
