### ISSUE TITLE
C++ comment style unrecognized, defaults to "#"

### ISSUE THREAD

**Issue by hassanalinali** [micro-editor/comment-plugin#15]
The c++ comment is defined as "// %s" but unfortunately it defaults to "# %s".

I've tested the other languages and they work as intended, except this one.

**Comment by zyedidia** [comment]
This is an issue that will be addressed with a new release of the comment plugin. It is fixed on master if you want to simply clone this repo into `~/.config/micro/plugins` as the `comment` directory.

**Comment by sum01** [comment]
This is fixed @hassanalinali
