### ISSUE TITLE
Commenting doesn't work when selection goes from end to start of line

### ISSUE THREAD

**Issue by samdmarshall** [micro-editor/comment-plugin#3]
When I select from the end of the line to start of the line, the commenting plugin doesn't cause a comment to be written on the selected text, but it does when selecting from start of the line to the end of the line.

**Comment by zyedidia** [comment]
I'm not having this issue. Could you give more specific instructions for reproducing the bug?

**Comment by samdmarshall** [comment]
I have mapped `"CtrlUnderscore"` to `"comment.comment"`, it only applies comments when I select text down, not up. Meaning, if I select lines 3 to 5, I can make the key-combo apply the comment formatting; however if I select lines 5 to 3, then it won't work.

**Comment by zyedidia** [comment]
Ok thanks, I thought you meant backwards selection on a single line. I'm now experiencing the issue.
