### ISSUE TITLE
attempt to call a non-function object

### ISSUE THREAD

**Issue by jahoyne** [micro-editor/comment-plugin#31]
Version 1.0.6 gives the error below when starting `micro`,  otherwise the comment plugin functions as expected within the editor

```
comment:102: attempt to call a non-function object
stack traceback:
	comment:102: in main chunk
	[G]: ?

Press enter to continue
```

**Comment by zyedidia** [comment]
This plugin is distributed by default with micro 2.0 and should not be installed unless you are using micro <=1.4.1. What version of micro are you using?

**Comment by jahoyne** [comment]
Thanks for the information, problem solved.

Apologies for not providing the essential info initially.

```
john@jon ~ $ micro --version
Version: 2.0.1
Commit hash: 7c71995
Compiled on February 15, 2020
```

I deleted `~/.config/micro/plug/comments` and, just as you say, found comments working correctly. 

Greetings from Scotland

**Comment by zyedidia** [comment]
Sounds good! Feel free to open more issues if you find other problems.
