### ISSUE TITLE
"Comment  is already installed but out-of-date" but then "unable to find a matching version for "comment"

### ISSUE THREAD

**Issue by MostHated** [micro-editor/comment-plugin#34]
Hello,
    I went to install comment, but then it said it was already installed but out of date. So I went to update it, but it said there was no version found.

```sh
> plugin install comment
comment  is already installed but out-of-date: use 'plugin update  comment ' to update
Nothing to install / update

> plugin update comment
Checking for plugin updates
unable to find a matching version for "comment"
```

<details>
<summary>Screenshot</summary>

![](https://i.imgur.com/wV2VCDG.png)

</details>

```sh
micro --version
Version: 2.0.9-dev.52
Commit hash: 6f949fe9
Compiled on March 14, 2021
```

Thanks,
-MH

**Comment by zyedidia** [comment]
After micro v2 comment should be provided by default with micro so there’s no need to install it separately.
