### ISSUE TITLE
Python files are using /* this */ instead of # this

### ISSUE THREAD

**Issue by AndydeCleyre** [micro-editor/comment-plugin#4]
Triggering the comment plugin inside a python file (`something.py`) uses slashes and asterisks instead of the hash symbol for comments.

**Comment by zyedidia** [comment]
It appears to be working for me. What version of micro are you using?

**Comment by AndydeCleyre** [comment]
`1.1.4`

**Comment by AndydeCleyre** [comment]
Looking at the code, it seems this must mean that this is true:

```lua
v.Buf.Settings["commenttype"] == nil
```

and this is false:

```lua
ft[v.Buf.Settings["filetype"]] ~= nil
```
