### ISSUE TITLE
Error with two open Windows

### ISSUE THREAD

**Issue by edelsonc** [micro-editor/comment-plugin#8]
The comment function won't work if there are two open windows in a micro session. By this I mean if you open a file `micro foo.bar` then `CtrlT`, `CtrlO` a new file and try to comment, the following error is returned

```
<string>:39: attempt to index a non-table object(nil)
stack traceback:
        <string>:39: in function 'commentLine'
        <string>:83: in main chunk
        [G]: ?
```

**Comment by id777** [comment]
SAME issue. If there are 2+ opened tabs in micro, plugin fail. Please fix

**Comment by sum01** [comment]
I don't think this is still an issue. I've tried and I can't reproduce it on comment v1.0.6
